input:
  mc:
    path: ["tests_run/test_mc.root"]     # Path to MC ROOT file
    tree: "DecayTree"                                                                                                  # Name of the MC TTree

  data:
    path: ["tests_run/test_data.root"]   # Path to Data ROOT file
    tree: "DecayTree"                      # Name of the Data TTree
    sweights_name: "sweight_sig"         # Signal weights branch for Data

  path_xlabels: "src/mcreweight/utils/default_xlabels.yaml"  # Optional labels for plotting

variables:
  training_vars:
    - "B_DTF_Jpsi_P"
    - "B_DTF_Jpsi_PT"
    - "nPVs"
    - "nLongTracks"

  monitoring_vars:
    - "B_PHI"
    - "B_ETA"

reweighting:
  methods:
    - "ONNXGB"
    - "GB"
    - "NN"
    - "Bins"
  sample: "bd_jpsikst_ee"                   # Label for the sample used
  transform: "yeo-johnson"                  # Data transformation method for XGB and NN
  clip_weights: true                        # Whether to clip extreme weights for stability
  n_trials: 5                               # Number of optuna trials for hyperparameter tuning (set to 0 to disable) 
  n_folds: 5                                # Number of folds for k-folding
  test_size: 0.35                           # Test size for train/test split
  n_bins: 20                                # Number of bins for Bins method  
  n_neighs: 5                               # Number of neighbors for Bins reweighting 
  shap: true                                # Whether to compute SHAP values for the reweighting model

output:
  weightsdir: "weights"                   # Optional: overrides MCREWEIGHTS_DATA_ROOT
  plotdir: "plots"                        # Directory for saving plots
