X_LABELS = {
    "B_DTF_Jpsi_M": r"$DTF M(B) [MeV/c^{2}]$",
    "B_DTF_Jpsi_P": r"$DTF P(B) [MeV/c]$",
    "B_DTF_Jpsi_PT": r"$DTF P_{T}(B) [MeV/c]$",
    "B_M": r"$M(B) [MeV/c^{2}]$",
    "B_P": r"$P(B) [MeV/c]$",
    "B_PT": r"$P_{T}(B) [MeV/c]$",
    "B_ETA": r"$\eta(B)$",
    "nLongTracks": "Number of Long Tracks",
    "nPVs": "Number of Primary Vertices",
    "nEcalClusters": "Number of Ecal Clusters",
    "nFTClusters": "Number of SciFi Clusters",
    "nVTClusters": "Number of Velo Clusters",
    "eCalTot/nEcalClusters": r"$\frac{E_{ECAL}}{N_{ECAL} clusters}$",
    "nHits": "Number of Hits",
    "log(B_CHI2DOF)": r"$\log(\chi^{2}/dof(B))$",
    "log(abs(B_BPVFD))": r"$\log(FD(B))$",
    "log(B_BPVFDCHI2)": r"$\log(FD\chi^{2}(B))$",
    "log(B_BPVLTIME)": r"$\log(LTIME(B))$",
    "log(B_BPVIP)": r"$\log(IP(B))$",
    "log(B_BPVIPCHI2)": r"$\log(IP\chi^{2}(B))$",
}
